[versions]
mod-version = "1.0.0"

# Fabric
minecraft = "1.21.5"
yarn-mappings = "1.21.5+build.1"
fabric-loader = "0.18.2"

# Loom
loom = "1.14-SNAPSHOT"

# Meteor
meteor = "1.21.5-SNAPSHOT"

[libraries]
# Fabric base
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

# Meteor client
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
